import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Vazirmatn } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * :::: config fonts ::::
 */
const pinar = localFont({
    src: "../assets/pinar.woff2",
    variable: "--font-pinar",
});

const vazirmatn = Vazirmatn({
    variable: "--font-vazirmatn",
    subsets: ["latin"],
});

const geist = Geist({
    variable: "--font-geist",
    subsets: ["latin"],
});

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * :::: metadata ::::
 */
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * :::: root layout ::::
 */
export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" dir="ltr" className="dark">
            <body className={`${pinar.variable} ${vazirmatn.variable} ${geist.variable}`}>
                <div className="text-3xl font-pinar font-bold bg-red-500">فونت پینار</div>
                <div className="text-3xl font-vazirmatn font-bold bg-red-500">فونت وزیر</div>
                <div className="text-3xl font-geist font-bold bg-red-500">geist font</div>
                {children}
            </body>
        </html>
    );
}
