import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * :::: config fonts ::::
 */
const PinarFont = localFont({
  src: "../assets/pinar.woff2",
});

const GeistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const GeistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * :::: metadata ::::
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * :::: root layout ::::
 */
export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
      <html lang="fa" dir="rtl" className="dark">
      <body className={`${PinarFont.className} ${GeistSans.variable} ${GeistMono.variable} bg-primary`}>{children}</body>
      </html>
  );
}
